In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('C:/Users/Sasha/Downloads/car_fuel_efficiency.csv')

In [59]:
pd.__version__

'2.2.3'

In [60]:
print(len(data))

9704


In [61]:
print(data.shape)

(9704, 11)


In [62]:
data.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [63]:
data['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [64]:
data.isnull().any().sum()

np.int64(4)

In [65]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [66]:
data.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [67]:
data['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [68]:
data['horsepower'].median()

149.0

In [69]:
data['horsepower'].value_counts().head(2)

horsepower
152.0    142
145.0    141
Name: count, dtype: int64

In [70]:
data['horsepower'].isna().sum()

np.int64(708)

In [73]:
data['horsepower'] = data['horsepower'].fillna(152)

In [74]:
data['horsepower'].isna().sum()

np.int64(0)

In [76]:
data['horsepower'].median()

152.0

In [6]:
data_x = data.loc[data['origin']=='Asia', ['vehicle_weight', 'model_year']]

In [7]:
X = data_x.head(7)

In [8]:
type(X)

pandas.core.frame.DataFrame

In [9]:
X = X.to_numpy()

In [10]:
type(X)

numpy.ndarray

In [11]:
XTX = X.T@X

In [12]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [13]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [14]:
XTX_i = np.linalg.inv(XTX)

In [15]:
XTX@XTX_i

array([[1., 0.],
       [0., 1.]])

In [16]:
Y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [17]:
Y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [18]:
W = (XTX_i@X.T)@Y

In [20]:
W_sum = W.sum()

In [21]:
W_sum

np.float64(0.5187709081074007)